#!/bin/bash

cat >> /etc/apt/sources.list.d/nginx.list << EOF
deb [arch=amd64] http://nginx.org/packages/mainline/ubuntu/ bionic nginx
deb-src http://nginx.org/packages/mainline/ubuntu/ bionic nginx
EOF

(cd /tmp && wget http://nginx.org/keys/nginx_signing.key && sudo apt-key add nginx_signing.key && rm nginx_signing.key)
apt -y update
apt -y install nginx
apt -y install awscli
apt -y autoremove

# sync dhparam.pem file
rm -f /etc/ssl/certs/dhparam.pem
aws s3 sync s3://coronafriend-secure/dhparam.pem /etc/ssl/certs/dhparam.pem

# Remove index files
rm -f /var/www/html/index.html
rm -f /var/www/html/index.nginx-debian.html


# Remove existing %CORONAFRIEND_DOMAIN%.html File
if [ -f "/var/www/html/%CORONAFRIEND_DOMAIN%.html" ]; then
    rm -f /var/www/html/%CORONAFRIEND_DOMAIN%.html
fi

# Remove exiting root nginx file
rm -rf /etc/nginx/nginx.conf

# Remove exiting htpasswd nginx file
rm -rf /etc/nginx/.htpasswd

rm -rf /var/www/domains/%CORONAFRIEND_DOMAIN%

# Setup Domain Folders
if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%
fi

if [ ! -d "/var/www/domains/%CORONAFRIEND_DOMAIN%/public" ]; then
    mkdir -p /var/www/domains/%CORONAFRIEND_DOMAIN%/public
fi
